name = "provideo-platform"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "8869a282-272b-4b91-abdd-d14de4a5e3e8"
